server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://${HOST_EUREKA}:8761/eureka
spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          lower-case-service-id: true
#          enabled: true
